### ISSUE TITLE
Feature requests allowed?

### ISSUE THREAD

**Issue by richard-kramer** [dominikks/discord-soundboard-bot#4]
@dominikks Are feature requests generally allowed and do you even have time to look into them? 

My friendgroup and I started using this Board and really like it. It's the only good selfhosted soundboard option we could find. But we also found a few usability "shortcomings" we would like to see improved. If allowed, I would add them as separate issues. Maybe I could even help with development, but I'm not firm in neither Rust nor Angular.

**Comment by dominikks** [comment]
I'm glad you're enjoying the soundboard! Sure, feature requests are definitely welcome, so feel free to create issues with your suggestions. 

However, I can't guarantee that I'll implement them. I can definitely spare some time to look into them and give feedback. If and when I can implement some of them depends on the scope of the changes, since I only work on this project in my spare time. If you're willing to make a PR that would probably speed things up!

**Comment by richard-kramer** [comment]
I created some issues with ideas/things that bothered me:

- #5
- #6
- #7
- #8
- #9

These are pretty unrefined. I could further refine acceptance criteria or dump more details into them, but I would also like to wait to hear your thoughts on them, before starting anything.
