### ISSUE TITLE
Feature: persisten API token

### ISSUE THREAD

**Issue by richard-kramer** [dominikks/discord-soundboard-bot#9]
Currently, the bearer token expires after a week and AutoHotkey-scripts as well as possible external integrations have to be regenerated/updated with a new token. It would be nice, if a user had the possibility to generate a persistent token, they could use indefinitely.

**Comment by dominikks** [comment]
That definitely makes sense to me. IIRC the tokens do not give access to admin functionality (like deleting or uploading sounds) anyway, so it should not be a big problem to keep them valid indefinitely.

One thing to keep in mind is that the token is regenerated everytime a new AutoHotkey-script is created. It might make sense to split this functionality up, so that an existing token can be reused (e.g. for creating multiple different scripts) and is only regenerated on demand.

**Comment by richard-kramer** [comment]
Also, Management of existing tokens would be required, so they can be invalidated if needed. 
I'm also not sure on regenerating scripts with the same tokens, as this would require storing them in plain text, which I would consider unsecure.

**Comment by dominikks** [comment]
Currently, each user can only have a single token. Generating a new token automatically invalidates the old one. Thus, simply allowing the user to regenerate the token on demand would be enough in terms of token management imo.

W.r.t. storing the token: the auth token needs to be stored in plain text in the AutoHotkey script. Currently, it is also stored in plain text in the database. In theory, we could store a hash of the token in the database instead. This would prevent anyone from impersonating the user if the token ever gets stolen from the database. However, since the token only allows playing sounds and creating recordings (and none of the admin functionality as well as no downloading of recordings), I don't think protecting the tokens is very critical. I am open to switching to hashed tokens nonetheless.

**Comment by richard-kramer** [comment]
True, I may be a bit rigid in my "best practices" 😅. One overridable token sounds good to me.
